apiVersion: apps/v1
kind: Deployment
metadata:
  name: revolut
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: revolut
  template:
    metadata:
      labels:
        app: revolut
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1a
                      - us-east-1b
                      - us-east-1c
      containers:
        - name: revolut-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}