apiVersion: v1
kind: Service
metadata:
  name: revolut-service
spec:
  selector:
    app: revolut
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}