spring:
  datasource:
    url: "${DB_URL}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_ROOT_PASSWORD}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: "update"

server:
  port: "${PORT}"
#  servlet:
#    contextPath: "/api/v1"
